# User Story 15
version: '3.8' # User Story 6

services:
  mongodb:
    image: mongo:latest
    container_name: pim_database
    restart: always
    ports:
      - "27017:27017"
    environment: # User Story 7
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db # Persistente Speicherung der Daten

volumes:
  mongodb_data:
